# Generated by Django 5.2 on 2025-04-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_tweet_title_tweet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
